<a href="https://colab.research.google.com/github/Mohamed-Shawky281/Customer-Churn-Classification-AI-NBE-internship/blob/Mekawy/Churn_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ML Project - Machine Learning Pipeline on a Customer Churn Classification Dataset

importing neccessary libraries

## Importing the Dataset

In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
##import matplotlib.pyplot as plt
##from sklearn.preprocessing import StandardScaler, LabelEncoder
##from imblearn.over_sampling import SMOTE
##from sklearn.model_selection import train_test_split

importing the dataset

In [12]:
df=pd.read_excel('/content/credit_card_churn_dataset_V4.xlsx')

# Dataset Analysis

we then know the size/dimensions of the dataset

In [13]:
print("Dataset dimensions:",df.shape)

Dataset dimensions: (20000, 60)

Therefore, the dataset size and dimensions is **20000 rows** and **60 coloumns (fields) including the target**

In [14]:
df.head()

,index,monthly_spend_cash,monthly_spend_payments,monthly_spend_installments,monthly_spend_subscriptions,monthly_spend_travel,monthly_spend_dining,monthly_spend_shopping,total_spend_last_month,total_spend_last_3_months,...,marital_status,education_level,employment_status,num_dependents,residence_type,years_at_residence,months_since_last_txn,utilization_ratio,inactivity_flag,month_key
0,5464,4664.0,7438.0,15398.000000,760,4884.056742,2211,6555.000000,40001,134147.488984,...,Single,Master,Unemployed,3,Owned,8,4,0.052633,1,2023-01
1,2042,NaN,8252.0,18864.429771,665,2970.000000,920,6430.319172,32342,101638.757719,...,Married,Master,Unemployed,1,Owned,15,5,0.063416,1,2023-01
2,8669,1408.0,5199.0,4964.000000,882,1167.000000,2418,4967.000000,21005,52898.328993,...,Single,Master,Employed,0,Owned,9,2,0.067758,0,2023-01
3,1115,NaN,1837.0,18270.000000,722,4808.275207,43,5992.000000,30275,86390.416083,...,Married,Master,Self-Employed,0,Rented,9,5,0.058221,1,2023-01
4,4078,4134.0,7530.0,18272.775610,166,3256.000000,2736,7506.437574,23050,74438.420532,...,Married,Master,Employed,4,Rented,2,0,0.057625,0,2023-01

as seen from  the sample fo the data some fields have null values aka **NaN** which will then be managed

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 60 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   index                               20000 non-null  int64
 1   monthly_spend_cash                  17985 non-null  float64
 2   monthly_spend_payments              18030 non-null  float64
 3   monthly_spend_installments          18482 non-null  float64
 4   monthly_spend_subscriptions         20000 non-null  int64
 5   monthly_spend_travel                20000 non-null  float64
 6   monthly_spend_dining                20000 non-null  int64
 7   monthly_spend_shopping              20000 non-null  float64
 8   total_spend_last_month              20000 non-null  int64
 9   total_spend_last_3_months           20000 non-null  float64
 10  total_spend_last_6_months           20000 non-null  float64
 11  total_spend_last_year               20000 non-null  float64
 12  average_monthly_spend               20000 non-null  float64
 13  max_monthly_spend                   20000 non-null  float64
 14  min_monthly_spend                   20000 non-null  float64
 15  average_transaction_value           15993 non-null  float64
 16  num_transactions_last_month         20000 non-null  int64
 17  num_transactions_last_3_months      20000 non-null  int64
 18  num_transactions_last_6_months      20000 non-null  int64
 19  num_transactions_last_year          20000 non-null  int64
 20  average_monthly_transactions        20000 non-null  int64
 21  max_monthly_transactions            20000 non-null  int64
 22  min_monthly_transactions            20000 non-null  int64
 23  decreasing_spend_trend              20000 non-null  int64
 24  spend_volatility                    20000 non-null  object
 25  recent_large_transactions           20000 non-null  int64
 26  use_of_credit_card_for_emergencies  20000 non-null  int64
 27  frequent_late_payments              20000 non-null  int64
 28  churn                               20000 non-null  int64
 29  expiration_date                     20000 non-null  datetime64[ns]
 30  acc_ref_num                         20000 non-null  int64
 31  previous_cards                      20000 non-null  int64
 32  longevity_in_months                 20000 non-null  int64
 33  feature_1                           20000 non-null  float64
 34  feature_2                           20000 non-null  int64
 35  feature_3                           15993 non-null  float64
 36  credit_limit                        20000 non-null  int64
 37  credit_limit_utilization            20000 non-null  float64
 38  average_payment_delay               20000 non-null  int64
 39  monthly_active_days                 20000 non-null  float64
 40  num_other_products                  20000 non-null  int64
 41  account_types                       20000 non-null  object
 42  loyalty_score                       17985 non-null  float64
 43  transaction_frequency               20000 non-null  int64
 44  total_bank_balance                  17985 non-null  float64
 45  act_ref_num                         20000 non-null  object
 46  plastic_masked_pan                  20000 non-null  object
 47  cust_id                             20000 non-null  object
 48  age                                 20000 non-null  int64
 49  gender                              20000 non-null  object
 50  marital_status                      20000 non-null  object
 51  education_level                     20000 non-null  object
 52  employment_status                   20000 non-null  object
 53  num_dependents                      20000 non-null  int64
 54  residence_type                      20000 non-null  object
 55  years_at_residence                  20000 non-null  int64
 56  months_since_last_txn               20000 non-null  int64
 57  utilization_ratio                   20000 non-null  float64
 58  inactivity_flag                     20000 non-null  int64
 59  month_key                           20000 non-null  object
dtypes: datetime64[ns](1), float64(19), int64(29), object(11)
memory usage: 9.2+ MB

if there were to be a single value in a field that is the same across all the records we were to delete it, but its not the case here.

In [16]:
df.isnull().sum()

index                                    0
monthly_spend_cash                    2015
monthly_spend_payments                1970
monthly_spend_installments            1518
monthly_spend_subscriptions              0
monthly_spend_travel                     0
monthly_spend_dining                     0
monthly_spend_shopping                   0
total_spend_last_month                   0
total_spend_last_3_months                0
total_spend_last_6_months                0
total_spend_last_year                    0
average_monthly_spend                    0
max_monthly_spend                        0
min_monthly_spend                        0
average_transaction_value             4007
num_transactions_last_month              0
num_transactions_last_3_months           0
num_transactions_last_6_months           0
num_transactions_last_year               0
average_monthly_transactions             0
max_monthly_transactions                 0
min_monthly_transactions                 0
decreasing_spend_trend                   0
spend_volatility                         0
recent_large_transactions                0
use_of_credit_card_for_emergencies       0
frequent_late_payments                   0
churn                                    0
expiration_date                          0
acc_ref_num                              0
previous_cards                           0
longevity_in_months                      0
feature_1                                0
feature_2                                0
feature_3                             4007
credit_limit                             0
credit_limit_utilization                 0
average_payment_delay                    0
monthly_active_days                      0
num_other_products                       0
account_types                            0
loyalty_score                         2015
transaction_frequency                    0
total_bank_balance                    2015
act_ref_num                              0
plastic_masked_pan                       0
cust_id                                  0
age                                      0
gender                                   0
marital_status                           0
education_level                          0
employment_status                        0
num_dependents                           0
residence_type                           0
years_at_residence                       0
months_since_last_txn                    0
utilization_ratio                        0
inactivity_flag                          0
month_key                                0
dtype: int64